# Generated by Django 4.2.4 on 2023-12-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminario_app', '0002_alter_inscrito_fecha_inscripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='telefono',
            field=models.IntegerField(max_length=15),
        ),
    ]
