# Generated by Django 4.2.4 on 2023-12-17 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminario_app', '0006_alter_inscrito_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='telefono',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(100000000)]),
        ),
    ]
